import type { DatasetImportRecord, DatasetItem, DatasetListItem } from "./shared";

export const mockDatasets: DatasetListItem[] = [
  {
    id: "dataset-service-qa",
    name: "客服问答评测集",
    description: "售后场景评测数据",
    owner_id: "user-admin",
    owner_name: "admin",
    group_id: "group-product",
    created_at: "2026-05-20T09:30:00",
    updated_at: "2026-05-27T10:30:00",
    knowledge_bases: [{ id: "kb-after-sales", name: "售后知识库" }],
    sample_count: 128,
    source_stats: { upload: 90, manual: 20, flowback: 18 },
  },
  {
    id: "dataset-model-provider",
    name: "模型供应商问答集",
    description: "配置类问题评测",
    owner_id: "user-admin",
    owner_name: "admin",
    group_id: "group-rd",
    created_at: "2026-05-19T14:00:00",
    updated_at: "2026-05-26T18:20:00",
    knowledge_bases: [{ id: "kb-model-config", name: "模型配置库" }],
    sample_count: 56,
    source_stats: { upload: 40, manual: 8, flowback: 8 },
  },
];

export const mockDatasetItems: Record<string, DatasetItem[]> = {
  "dataset-service-qa": [
    {
      id: "item-001",
      dataset_id: "dataset-service-qa",
      case_id: "case_001",
      question: "如何配置模型供应商？",
      question_type: "操作问答",
      ground_truth: "进入模型供应商页面，新增 API Key，并选择默认模型。",
      key_points: "进入模型供应商页面；新增 API Key；选择默认模型",
      reference_context: "模型供应商配置说明中描述了新增供应商、填写 API Key 和设为默认模型的步骤。",
      reference_doc: "模型配置手册",
      reference_doc_ids: ["doc_001"],
      reference_chunk_ids: ["chunk_001", "chunk_002"],
      generate_reason: "答案依据来自模型配置手册相关片段。",
      source: "upload",
      created_at: "2026-05-26T09:00:00",
      updated_at: "2026-05-27T09:30:00",
      created_by: "王博超",
    },
    {
      id: "item-002",
      dataset_id: "dataset-service-qa",
      case_id: "case_002",
      question: "为什么检索不到文档？",
      question_type: "排障问答",
      ground_truth: "先检查知识库同步状态、文档解析状态和检索范围，再确认用户是否有对应知识库权限。",
      key_points: "同步状态；解析状态；检索范围；权限",
      reference_context: "排障手册中说明检索失败通常与同步、解析、权限或筛选条件有关。",
      reference_doc: "排障手册",
      reference_doc_ids: ["doc_020"],
      reference_chunk_ids: ["chunk_091"],
      source: "flowback",
      source_session_id: "session_20260527_001",
      created_at: "2026-05-27T08:20:00",
      updated_at: "2026-05-27T08:20:00",
      created_by: "算法回流",
    },
    {
      id: "item-003",
      dataset_id: "dataset-service-qa",
      case_id: "case_003",
      question: "如何删除数据源？",
      question_type: "操作问答",
      ground_truth: "进入数据源管理页面，找到目标数据源，点击删除并在二次确认后完成删除。",
      reference_doc: "数据源操作指南",
      reference_doc_ids: ["doc_033"],
      reference_chunk_ids: ["chunk_120"],
      source: "manual",
      created_at: "2026-05-26T15:40:00",
      updated_at: "2026-05-26T15:40:00",
      created_by: "王博超",
    },
  ],
  "dataset-model-provider": [
    {
      id: "item-101",
      dataset_id: "dataset-model-provider",
      case_id: "case_101",
      question: "API Key 验证失败怎么办？",
      question_type: "排障问答",
      ground_truth: "检查 API Key 是否复制完整、供应商 Base URL 是否正确，以及当前账号是否有调用额度。",
      key_points: "API Key 完整性；Base URL；额度",
      reference_doc: "模型配置手册",
      reference_doc_ids: ["doc_101"],
      reference_chunk_ids: ["chunk_201"],
      source: "upload",
      created_at: "2026-05-26T10:00:00",
      updated_at: "2026-05-26T10:30:00",
      created_by: "王博超",
    },
  ],
};

export const mockImportRecords: Record<string, DatasetImportRecord[]> = {
  "dataset-service-qa": [
    {
      id: "import-001",
      file_name: "客服问答评测集.xlsx",
      file_type: "xlsx",
      file_size: 34576,
      import_status: "success",
      success_count: 90,
      failed_count: 3,
      created_by: "王博超",
      created_at: "2026-05-26T09:00:00",
    },
  ],
};
