// all_models text orm/models.go text model text，text dbmigrate migrate / create -with-ddl text DDL text。
// text Model text models.go text，text AllModelsForDDL / TableNamesForDDL text。

package orm

// AllModelsForDDL text model text，text DDL text。
func AllModelsForDDL() []interface{} {
	return []interface{}{
		&VisibilityModel{},
		&ACLModel{},
		&KBModel{},
		&ACLGroupModel{},
		&UserGroupModel{},
		&Prompt{},
		&DefaultPrompt{},
		&UserDisabledTool{},
		&MultiAnswersSwitch{},
		&Conversation{},
		&ChatHistory{},
		&MultiAnswersChatHistory{},
		&SystemMemory{},
		&SystemUserPreference{},
		&UserPersonalizationSetting{},
		&SkillResource{},
		&ResourceUpdateTask{},
		&SkillReviewSchedulerState{},
		&ConversationIdleEvent{},
		&ResourceSessionSnapshot{},
		&ResourceSuggestion{},
		&SkillShareTask{},
		&SkillShareItem{},
		&AgentThread{},
		&AgentUserActiveThread{},
		&AgentThreadRecord{},
		&AgentThreadRound{},
		&Dataset{},
		&DefaultDataset{},
		&EvalSetShard{},
		&EvalSet{},
		&EvalSetItem{},
		&EvalSetImportPreview{},
		&AsyncJob{},
		&DefaultModelProvider{},
		&DefaultModel{},
		&UserModelProvider{},
		&UserModelProviderGroup{},
		&UserModelProviderGroupModel{},
		&UserSelectedModel{},
		&Document{},
		&Task{},
		&UploadSession{},
		&UploadedFile{},
		&Word{},
		&WordGroupConflict{},
	}
}

// TableNamesForDDL text AllModelsForDDL text，text DROP TABLE（text）。
func TableNamesForDDL() []string {
	return []string{
		"acl_visibility",
		"acl_rows",
		"acl_kbs",
		"acl_user_groups",
		"prompts",
		"default_prompts",
		"user_disabled_tools",
		"multi_answers_switches",
		"conversations",
		"chat_histories",
		"multi_answers_chat_histories",
		"system_memories",
		"system_user_preferences",
		"user_personalization_settings",
		"skill_resources",
		"resource_update_tasks",
		"skill_review_scheduler_state",
		"conversation_idle_events",
		"resource_session_snapshots",
		"resource_suggestions",
		"skill_share_tasks",
		"skill_share_items",
		"agent_threads",
		"agent_user_active_threads",
		"agent_thread_records",
		"agent_thread_rounds",
		"datasets",
		"default_datasets",
		"eval_set_shards",
		"eval_sets",
		"eval_set_items",
		"eval_set_import_previews",
		"async_jobs",
		"default_model_providers",
		"default_models",
		"user_model_providers",
		"user_model_provider_groups",
		"user_model_provider_group_models",
		"user_selected_models",
		"documents",
		"tasks",
		"upload_sessions",
		"uploaded_files",
		"words",
		"word_group_conflicts",
	}
}
