package main

import (
	"encoding/json"
	"os"
	"strings"
)

func writeServiceEndpointFiles(paths RuntimePaths, endpoints ServiceEndpoints) error {
	body, err := json.MarshalIndent(endpoints, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(paths.ServiceEndpointsJSON, append(body, '\n'), 0o644); err != nil {
		return err
	}
	return os.WriteFile(paths.ServiceEndpointsEnv, []byte(serviceEndpointsEnv(endpoints)), 0o644)
}

func serviceEndpointsEnv(endpoints ServiceEndpoints) string {
	values := map[string]string{
		"LAZYMIND_ENDPOINT_HOST_AUTH_SERVICE_BASE_URL":          endpoints.Host.AuthServiceBaseURL,
		"LAZYMIND_ENDPOINT_HOST_CORE_BASE_URL":                  endpoints.Host.CoreBaseURL,
		"LAZYMIND_ENDPOINT_HOST_DOCUMENT_SERVICE_BASE_URL":      endpoints.Host.DocumentServiceBaseURL,
		"LAZYMIND_ENDPOINT_HOST_PROCESSOR_BASE_URL":             endpoints.Host.ProcessorBaseURL,
		"LAZYMIND_ENDPOINT_HOST_CHAT_BASE_URL":                  endpoints.Host.ChatBaseURL,
		"LAZYMIND_ENDPOINT_HOST_EVO_BASE_URL":                   endpoints.Host.EvoBaseURL,
		"LAZYMIND_ENDPOINT_HOST_OFFICE_CONVERT_URL":             endpoints.Host.OfficeConvertURL,
		"LAZYMIND_ENDPOINT_HOST_POSTGRES_ADDRESS":               endpoints.Host.PostgresAddress,
		"LAZYMIND_ENDPOINT_CONTAINER_AUTH_SERVICE_BASE_URL":     endpoints.Container.AuthServiceBaseURL,
		"LAZYMIND_ENDPOINT_CONTAINER_CORE_BASE_URL":             endpoints.Container.CoreBaseURL,
		"LAZYMIND_ENDPOINT_CONTAINER_DOCUMENT_SERVICE_BASE_URL": endpoints.Container.DocumentServiceBaseURL,
		"LAZYMIND_ENDPOINT_CONTAINER_PROCESSOR_BASE_URL":        endpoints.Container.ProcessorBaseURL,
		"LAZYMIND_ENDPOINT_CONTAINER_CHAT_BASE_URL":             endpoints.Container.ChatBaseURL,
		"LAZYMIND_ENDPOINT_CONTAINER_EVO_BASE_URL":              endpoints.Container.EvoBaseURL,
		"LAZYMIND_ENDPOINT_CONTAINER_OFFICE_CONVERT_URL":        endpoints.Container.OfficeConvertURL,
		"LAZYMIND_ENDPOINT_CONTAINER_POSTGRES_ADDRESS":          endpoints.Container.PostgresAddress,
	}
	order := []string{
		"LAZYMIND_ENDPOINT_HOST_AUTH_SERVICE_BASE_URL",
		"LAZYMIND_ENDPOINT_HOST_CORE_BASE_URL",
		"LAZYMIND_ENDPOINT_HOST_DOCUMENT_SERVICE_BASE_URL",
		"LAZYMIND_ENDPOINT_HOST_PROCESSOR_BASE_URL",
		"LAZYMIND_ENDPOINT_HOST_CHAT_BASE_URL",
		"LAZYMIND_ENDPOINT_HOST_EVO_BASE_URL",
		"LAZYMIND_ENDPOINT_HOST_OFFICE_CONVERT_URL",
		"LAZYMIND_ENDPOINT_HOST_POSTGRES_ADDRESS",
		"LAZYMIND_ENDPOINT_CONTAINER_AUTH_SERVICE_BASE_URL",
		"LAZYMIND_ENDPOINT_CONTAINER_CORE_BASE_URL",
		"LAZYMIND_ENDPOINT_CONTAINER_DOCUMENT_SERVICE_BASE_URL",
		"LAZYMIND_ENDPOINT_CONTAINER_PROCESSOR_BASE_URL",
		"LAZYMIND_ENDPOINT_CONTAINER_CHAT_BASE_URL",
		"LAZYMIND_ENDPOINT_CONTAINER_EVO_BASE_URL",
		"LAZYMIND_ENDPOINT_CONTAINER_OFFICE_CONVERT_URL",
		"LAZYMIND_ENDPOINT_CONTAINER_POSTGRES_ADDRESS",
	}
	var b strings.Builder
	b.WriteString("# Generated by lazymind-local. Do not edit.\n")
	for _, key := range order {
		b.WriteString(key)
		b.WriteString("=")
		b.WriteString(quoteEnvValue(values[key]))
		b.WriteString("\n")
	}
	return b.String()
}

func quoteEnvValue(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
