// Package plugin EventLoop handles plugin_step task lifecycle on the Go side.
// It extends handleTaskCreated in chat/conversation_logic.go to process
// agent_type='plugin_step' events with Plugin-specific session management.
package plugin

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"

	"gorm.io/gorm"

	"lazymind/core/common"
	"lazymind/core/common/orm"
	"lazymind/core/state"
	"lazymind/core/subagent"
)

// DefaultMode returns the configured plugin advance mode (auto|manual).
func DefaultMode() string { return defaultMode() }

func defaultMode() string {
	v := strings.TrimSpace(os.Getenv("LAZYMIND_PLUGIN_MODE"))
	if v == "manual" {
		return "manual"
	}
	return "auto"
}

// PluginStepParams are the task_created.params fields for plugin_step agent type.
type PluginStepParams struct {
	PluginID    string `json:"plugin_id"`
	StepID      string `json:"step_id"`
	SessionID   string `json:"session_id"`
	UserInput   string `json:"user_input"`
	IsColdStart bool   `json:"is_cold_start"`

	// RetryHint is a runtime instruction generated by ChatAgent for partial/full retries.
	// It is appended to the step objective before the SubAgent runs, and is NOT persisted
	// back to state.yml — it only affects the current execution.
	RetryHint string `json:"retry_hint,omitempty"`

	// PartialIndices maps artifact_key → list of list_index values that should be
	// overwritten (not appended) when the SubAgent saves those artifacts.
	// Nil / empty means full write (append for list, overwrite for single).
	// Example: {"material_images": [1]} — only slot entry at list_index=1 is replaced.
	PartialIndices map[string][]int `json:"partial_indices,omitempty"`
}

// asMap serialises the params into the generic map expected by subagent.RunRequest.Params.
func (p PluginStepParams) asMap() map[string]any {
	m := map[string]any{
		"plugin_id":     p.PluginID,
		"step_id":       p.StepID,
		"session_id":    p.SessionID,
		"user_input":    p.UserInput,
		"is_cold_start": p.IsColdStart,
	}
	if p.RetryHint != "" {
		m["retry_hint"] = p.RetryHint
	}
	if len(p.PartialIndices) > 0 {
		m["partial_indices"] = p.PartialIndices
	}
	return m
}

// PluginChatContext carries plugin identifiers threaded through the SubAgent event loop.
type PluginChatContext struct {
	SessionID string
	PluginID  string
	StepID    string
	ConvID    string
	UserID    string
}

// HandlePluginStepCreated processes a task_created event for agent_type='plugin_step'.
// It either creates (cold start) or resumes an existing plugin session,
// persists the sub_agent_task + plugin_session_step records,
// and launches the SubAgent goroutine.
// Returns (sessionID, taskID, error).
//
// NOTE: objective is stored as-is (raw template with {{...}} placeholders).
// Artifact injection is handled by the Python runner at execution time via
// _enrich_objective_with_artifacts(), avoiding the Go layer querying the DB
// for data that Python can fetch itself.
func HandlePluginStepCreated(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	convID, historyID, userID string,
	taskID, title, objective string,
	params PluginStepParams,
	inputKeys, outputKeys []string,
	llmConfig map[string]any,
	toolConfig map[string]any,
) (sessionID string, returnedTaskID string, err error) {
	pluginID := params.PluginID
	stepID := params.StepID
	isCold := params.IsColdStart
	returnedTaskID = taskID

	if isCold {
		existing, gErr := GetActiveSession(ctx, db, convID)
		if gErr != nil {
			return "", "", fmt.Errorf("plugin: check active session: %w", gErr)
		}
		if existing != nil {
			return "", "", fmt.Errorf("plugin: active session already exists (id=%s)", existing.ID)
		}
		psID := "ps_" + common.GenerateID()
		_, sErr := CreateSession(ctx, db, CreateSessionInput{
			SessionID:        psID,
			ConversationID:   convID,
			PluginID:         pluginID,
			TriggerHistoryID: historyID,
			CurrentStepID:    stepID,
			CreateUserID:     userID,
		})
		if sErr != nil {
			return "", "", fmt.Errorf("plugin: create session: %w", sErr)
		}
		sessionID = psID
	} else {
		sessionID = params.SessionID
		if sessionID == "" {
			return "", "", fmt.Errorf("plugin: session_id required for non-cold-start step")
		}
		if uErr := UpdateSessionCurrentStep(ctx, db, sessionID, stepID); uErr != nil {
			fmt.Printf("[Plugin] failed to update current_step: %v\n", uErr)
		}
	}

	// Inject artifacts from previous steps into objective, then append retry_hint if present.
	enrichedObjective := objective
	if params.RetryHint != "" {
		enrichedObjective += "\n\n--- Retry instruction (runtime only, not part of permanent prompt) ---\n" + params.RetryHint
	}

	// Create sub_agent_tasks record.
	rawParamsMap := map[string]any{
		"plugin_id":     pluginID,
		"step_id":       stepID,
		"session_id":    sessionID,
		"user_input":    params.UserInput,
		"is_cold_start": isCold,
	}
	if params.RetryHint != "" {
		rawParamsMap["retry_hint"] = params.RetryHint
	}
	if len(params.PartialIndices) > 0 {
		rawParamsMap["partial_indices"] = params.PartialIndices
	}
	rawParams, _ := json.Marshal(rawParamsMap)
	inputJSON, _ := json.Marshal(inputKeys)
	outputJSON, _ := json.Marshal(outputKeys)
	task, cErr := subagent.CreateTask(ctx, db, subagent.CreateTaskInput{
		TaskID:             taskID,
		ConversationID:     convID,
		TriggerHistoryID:   historyID,
		AgentType:          "plugin_step",
		Title:              pluginID + ":" + stepID,
		Objective:          enrichedObjective,
		Mode:               "manual",
		Params:             rawParams,
		InputArtifactKeys:  inputJSON,
		OutputArtifactKeys: outputJSON,
		WorkspacePath:      subagent.WorkspacePath(userID, taskID),
		CreateUserID:       userID,
	})
	if cErr != nil {
		return "", sessionID, fmt.Errorf("plugin: create sub_agent_task: %w", cErr)
	}

	// Create plugin_session_steps record.
	attempt, _ := NextAttempt(ctx, db, sessionID, stepID)
	if _, stepErr := CreateSessionStep(ctx, db, sessionID, stepID, task.ID, attempt); stepErr != nil {
		fmt.Printf("[Plugin] failed to create session step: %v\n", stepErr)
	}

	// Seed Redis status.
	_ = subagent.WriteStatus(ctx, stateStore, task.ID, map[string]any{
		"status": subagent.StatusPending, "progress": 0,
	})

	// Launch SubAgent goroutine.
	// input_artifact_keys, output_artifact_keys, and tools are NOT forwarded here:
	// the Python runner reads them from the DB task record and plugin_loader respectively.
	go subagent.Run(context.Background(), db, stateStore, subagent.RunRequest{
		TaskID:        task.ID,
		AgentType:     "plugin_step",
		WorkspacePath: task.WorkspacePath,
		Params: map[string]any{
			"plugin_id":  pluginID,
			"step_id":    stepID,
			"session_id": sessionID,
		},
		DBDSN:      subagent.DBDSN(),
		Resume:     false,
		LLMConfig:  llmConfig,
		ToolConfig: toolConfig,
	})

	return sessionID, task.ID, nil
}

// OnSubAgentDone is called when a plugin_step task reaches terminal status.
// It mirrors the step status and handles auto/manual advance logic.
func OnSubAgentDone(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	taskID, status, summary string,
	onSSE func(eventType string, payload map[string]any),
	pctx *PluginChatContext,
) {
	_ = UpdateStepStatus(ctx, db, taskID, status)

	if status == subagent.StatusInterrupted {
		// Interrupted steps are recoverable: put the session into waiting so
		// the frontend can resume via POST /plugin-sessions/{id}:advance.
		if pctx != nil {
			_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
			onSSE("step_waiting", map[string]any{
				"session_id":  pctx.SessionID,
				"step_id":     pctx.StepID,
				"interrupted": true,
			})
		}
		return
	}

	if status != subagent.StatusSucceeded {
		if pctx != nil {
			_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusFailed)
			onSSE("plugin_error", map[string]any{
				"session_id": pctx.SessionID,
				"step_id":    pctx.StepID,
				"message":    summary,
			})
		}
		return
	}

	if pctx == nil {
		return
	}

	if DefaultMode() == "auto" {
		go advanceAutoMode(ctx, db, stateStore, summary, onSSE, pctx)
	} else {
		_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
		onSSE("step_waiting", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
		})
	}
	// Write content_snapshot to all selected revisions for this step.
	go OnSubAgentDoneSnapshot(context.Background(), db, pctx)
}

// advanceAutoMode calls DriverAgent and either triggers a new ChatAgent turn or ends the session.
func advanceAutoMode(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	summary string,
	onSSE func(string, map[string]any),
	pctx *PluginChatContext,
) {
	verdict, reason := callDriverAgent(pctx.PluginID, pctx.StepID, summary, pctx.SessionID)
	switch verdict {
	case "DONE":
		_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusCompleted)
		onSSE("plugin_completed", map[string]any{
			"session_id": pctx.SessionID,
			"plugin_id":  pctx.PluginID,
		})
	case "FAIL":
		_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusFailed)
		onSSE("plugin_error", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
			"message":    reason,
		})
	default: // PASS, RETRY
		syntheticMsg := buildSyntheticMessage(verdict, pctx.StepID, reason)
		// Emit driver_input so the frontend renders the synthetic user message.
		onSSE("driver_input", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
			"verdict":    verdict,
			"message":    syntheticMsg,
		})
		// Notify frontend to open a resume SSE so it can receive the next chat turn.
		onSSE("auto_chat_started", map[string]any{
			"session_id":      pctx.SessionID,
			"conversation_id": pctx.ConvID,
		})
		go triggerNextChatTurn(pctx.ConvID, pctx.SessionID, pctx.PluginID, pctx.StepID,
			pctx.UserID, syntheticMsg)
	}
}

// buildSyntheticMessage produces the synthetic user message for ChatAgent on auto-advance.
func buildSyntheticMessage(verdict, stepID, reason string) string {
	r := strings.TrimSpace(reason)
	switch verdict {
	case "RETRY":
		return fmt.Sprintf("Step %s result unsatisfactory. %s Retry.", stepID, r)
	default:
		return fmt.Sprintf("Step %s completed. %s Proceed.", stepID, r)
	}
}

// triggerNextChatTurn sends a synthetic POST /conversations:chat to Go core to trigger
// the next ChatAgent round. This ensures history persistence, applyChatRuntimeConfigs,
// and all other Go-side pipeline steps run exactly as in a real user turn.
func triggerNextChatTurn(
	convID, sessionID, pluginID, currentStep, userID, syntheticMsg string,
) {
	coreURL := common.CoreSelfEndpoint() + "/conversations:chat"
	reqBody := map[string]any{
		"query":           syntheticMsg,
		"conversation_id": convID,
		// stream=true is required so that task_created events emitted by the ChatAgent
		// are written to the Redis SSE buffer and delivered to the frontend.
		// Non-streaming mode skips the event pipeline entirely.
		"stream": true,
		"mode":   "auto",
		"input":  []map[string]any{{"input_type": "text", "text": syntheticMsg}},
		"plugin_context": map[string]any{
			"session_id":   sessionID,
			"plugin_id":    pluginID,
			"current_step": currentStep,
			"advance":      false,
		},
	}
	body, _ := json.Marshal(reqBody)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, coreURL, bytes.NewReader(body))
	if err != nil {
		fmt.Printf("[Plugin] triggerNextChatTurn: build request: %v\n", err)
		return
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "text/event-stream")
	req.Header.Set("X-User-Id", userID)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		fmt.Printf("[Plugin] triggerNextChatTurn: send request: %v\n", err)
		return
	}
	defer resp.Body.Close()
	// Drain the SSE response body. We do not relay the stream anywhere; Go core
	// writes all events (including task_created) directly to Redis. Draining is
	// required to keep the connection alive until the upstream finishes.
	buf := make([]byte, 4096)
	for {
		if _, err := resp.Body.Read(buf); err != nil {
			break
		}
	}
}

// OnArtifactEvent is called when a plugin_step SubAgent emits an artifact event.
// It checks slot binding and writes plugin_slot_revisions if the artifact is bound.
// Caption embedded in the artifact value is written to sub_agent_artifacts.caption.
//
// For list-cardinality slots, the artifact value may carry a "list_index" field
// (written by save_artifact) that enables partial retry: only the revision at that
// index is replaced; other indices remain untouched.
// When "list_index" is absent the item is appended at the next available index.
func OnArtifactEvent(
	ctx context.Context,
	db *gorm.DB,
	taskID, artifactKey string,
	pctx *PluginChatContext,
) {
	if pctx == nil {
		return
	}
	slotID, cardinality := resolveSlotBinding(pctx.PluginID, artifactKey)
	if slotID == "" {
		return
	}
	attempt := 1
	step, _ := GetLatestStep(ctx, db, pctx.SessionID, pctx.StepID)
	if step != nil {
		attempt = step.Attempt
	}

	// For list slots, extract list_index from the artifact value if present.
	var listIndex *int
	if cardinality == "list" {
		listIndex = extractListIndex(ctx, db, taskID, artifactKey)
	}

	// Extract caption from artifact value and write it to sub_agent_artifacts.caption.
	// PostgreSQL does not support UPDATE with ORDER BY/LIMIT, so we first fetch the
	// target row's primary key (task_id + artifact_key + seq), then update by PK.
	if caption := extractCaption(ctx, db, taskID, artifactKey); caption != "" {
		var target orm.SubAgentArtifact
		if db.WithContext(ctx).
			Where("task_id = ? AND artifact_key = ?", taskID, artifactKey).
			Order("seq DESC").
			First(&target).Error == nil {
			_ = db.WithContext(ctx).Model(&orm.SubAgentArtifact{}).
				Where("task_id = ? AND artifact_key = ? AND seq = ?", target.TaskID, target.ArtifactKey, target.Seq).
				Update("caption", caption).Error
		}
	}

	rev, err := WriteSlotRevision(ctx, db,
		pctx.SessionID, slotID, artifactKey, pctx.StepID, attempt, cardinality, listIndex)
	if err != nil {
		fmt.Printf("[Plugin] WriteSlotRevision failed: %v\n", err)
		return
	}

	// Back-fill list_index into sub_agent_artifacts.value so that HideSlotItem
	// can match the artifact row by list_index when the user deletes an item.
	// This is needed for append-mode artifacts where Python does not yet know
	// the list_index assigned by Go (sort_order was not passed to save_artifact).
	if cardinality == "list" && rev != nil && rev.ListIndex != nil {
		backfillArtifactListIndex(ctx, db, taskID, artifactKey, *rev.ListIndex)
	}
}

// OnSubAgentDoneSnapshot back-fills artifact_seq on any AI slot revision that was
// written before the artifact row existed (i.e. artifact_seq is still NULL).
// This covers the race where WriteSlotRevision ran before save_artifact committed.
// Human revisions (change_source='human') are never touched.
func OnSubAgentDoneSnapshot(
	ctx context.Context,
	db *gorm.DB,
	pctx *PluginChatContext,
) {
	if pctx == nil {
		return
	}
	revisions, err := LoadSelectedSlots(ctx, db, pctx.SessionID)
	if err != nil {
		fmt.Printf("[Plugin] OnSubAgentDoneSnapshot: load slots: %v\n", err)
		return
	}

	step, _ := GetLatestStep(ctx, db, pctx.SessionID, pctx.StepID)
	if step == nil {
		return
	}

	for _, rev := range revisions {
		if rev.StepID != pctx.StepID || rev.Attempt != step.Attempt {
			continue
		}
		// Only fix AI revisions where artifact_seq was not resolved at write time.
		if rev.ChangeSource != "ai" || rev.ArtifactSeq != nil {
			continue
		}

		// Find the matching artifact row.
		var art orm.SubAgentArtifact
		if rev.ListIndex != nil {
			var candidates []orm.SubAgentArtifact
			db.WithContext(ctx).
				Where("task_id = ? AND artifact_key = ?", step.TaskID, rev.ArtifactKey).
				Order("seq DESC").
				Find(&candidates)
			for _, c := range candidates {
				var v map[string]any
				if json.Unmarshal(c.Value, &v) != nil {
					continue
				}
				var liInt int
				switch idx := v["list_index"].(type) {
				case float64:
					liInt = int(idx)
				case int:
					liInt = idx
				default:
					continue
				}
				if liInt == *rev.ListIndex {
					art = c
					break
				}
			}
			if art.TaskID == "" {
				continue
			}
		} else {
			if err := db.WithContext(ctx).
				Where("task_id = ? AND artifact_key = ?", step.TaskID, rev.ArtifactKey).
				Order("seq DESC").
				First(&art).Error; err != nil {
				continue
			}
		}

		seq := art.Seq
		if err := db.WithContext(ctx).Model(&orm.PluginSlotRevision{}).
			Where("id = ?", rev.ID).
			Update("artifact_seq", seq).Error; err != nil {
			fmt.Printf("[Plugin] OnSubAgentDoneSnapshot: backfill artifact_seq rev=%s: %v\n", rev.ID, err)
		}
	}
}

// extractListIndex reads the most recent artifact value for the given (taskID, artifactKey)
// and returns the list_index embedded in the JSON value, or nil if absent.
func extractListIndex(ctx context.Context, db *gorm.DB, taskID, artifactKey string) *int {
	var a orm.SubAgentArtifact
	err := db.WithContext(ctx).
		Where("task_id = ? AND artifact_key = ?", taskID, artifactKey).
		Order("seq DESC").
		First(&a).Error
	if err != nil {
		return nil
	}
	var v map[string]any
	if json.Unmarshal(a.Value, &v) != nil {
		return nil
	}
	raw, ok := v["list_index"]
	if !ok {
		return nil
	}
	switch idx := raw.(type) {
	case float64:
		i := int(idx)
		return &i
	case int:
		return &idx
	}
	return nil
}

// extractCaption reads the most recent artifact value for the given (taskID, artifactKey)
// and returns the caption string embedded in the JSON value, or "" if absent.
func extractCaption(ctx context.Context, db *gorm.DB, taskID, artifactKey string) string {
	var a orm.SubAgentArtifact
	err := db.WithContext(ctx).
		Where("task_id = ? AND artifact_key = ?", taskID, artifactKey).
		Order("seq DESC").
		First(&a).Error
	if err != nil {
		return ""
	}
	var v map[string]any
	if json.Unmarshal(a.Value, &v) != nil {
		return ""
	}
	if cap, ok := v["caption"].(string); ok {
		return strings.TrimSpace(cap)
	}
	return ""
}

// resolveSlotBinding looks up (slotID, cardinality) for an artifact key from the Python plugin API.
func resolveSlotBinding(pluginID, artifactKey string) (slotID, cardinality string) {
	endpoint := common.ChatServiceEndpoint()
	url := fmt.Sprintf("%s/api/plugin/slot-binding?plugin_id=%s&artifact_key=%s",
		endpoint, pluginID, artifactKey)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return "", ""
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", ""
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", ""
	}
	var result struct {
		SlotID      string `json:"slot_id"`
		Cardinality string `json:"cardinality"`
	}
	if json.NewDecoder(resp.Body).Decode(&result) != nil {
		return "", ""
	}
	return result.SlotID, result.Cardinality
}

// callDriverAgent posts to the Python DriverAgent endpoint and returns (verdict, reason).
// On any error defaults to ("PASS", "").
func callDriverAgent(pluginID, stepID, stepResult, sessionID string) (verdict, reason string) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	reqBody := map[string]any{
		"plugin_id":   pluginID,
		"step_id":     stepID,
		"step_result": stepResult,
		"session_id":  sessionID,
	}
	body, _ := json.Marshal(reqBody)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, driverEndpoint(), bytes.NewReader(body))
	if err != nil {
		return "PASS", ""
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "PASS", ""
	}
	defer resp.Body.Close()
	var result struct {
		Verdict string `json:"verdict"`
		Reason  string `json:"reason"`
	}
	if resp.StatusCode != http.StatusOK || json.NewDecoder(resp.Body).Decode(&result) != nil {
		return "PASS", ""
	}
	v := strings.ToUpper(strings.TrimSpace(result.Verdict))
	if v != "PASS" && v != "RETRY" && v != "DONE" && v != "FAIL" {
		return "PASS", result.Reason
	}
	return v, result.Reason
}

// driverEndpoint returns the DriverAgent URL.
func driverEndpoint() string {
	return common.ChatServiceEndpoint() + "/api/plugin/driver"
}

// backfillArtifactListIndex patches the most-recent sub_agent_artifacts row for
// (taskID, artifactKey) to embed {"list_index": listIndex} inside its value JSON.
// This ensures HideSlotItem can match artifacts by list_index even when the AI
// wrote the artifact in append-mode (no sort_order → no list_index in value at write time).
// Skipped silently if the row already contains the correct list_index.
func backfillArtifactListIndex(ctx context.Context, db *gorm.DB, taskID, artifactKey string, listIndex int) {
	var art orm.SubAgentArtifact
	if err := db.WithContext(ctx).
		Where("task_id = ? AND artifact_key = ?", taskID, artifactKey).
		Order("seq DESC").
		First(&art).Error; err != nil {
		return
	}
	var v map[string]any
	if json.Unmarshal(art.Value, &v) != nil {
		return
	}
	// Already correct — no update needed.
	if existing, ok := v["list_index"]; ok {
		switch idx := existing.(type) {
		case float64:
			if int(idx) == listIndex {
				return
			}
		case int:
			if idx == listIndex {
				return
			}
		}
	}
	v["list_index"] = listIndex
	newVal, err := json.Marshal(v)
	if err != nil {
		return
	}
	_ = db.WithContext(ctx).Model(&orm.SubAgentArtifact{}).
		Where("task_id = ? AND artifact_key = ? AND seq = ?", art.TaskID, art.ArtifactKey, art.Seq).
		Update("value", newVal).Error
}
