// Package plugin EventLoop handles plugin_step task lifecycle on the Go side.
// It extends handleTaskCreated in chat/conversation_logic.go to process
// agent_type='plugin_step' events with Plugin-specific session management.
package plugin

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"gorm.io/gorm"

	"lazymind/core/common"
	"lazymind/core/common/orm"
	"lazymind/core/modelconfig"
	"lazymind/core/state"
	"lazymind/core/store"
	"lazymind/core/subagent"
	"lazymind/core/taskcenter"
)

type chatStatusCacheEntry struct {
	Status string `json:"status"`
}

// PluginStepParams is the shared launch payload used by the v2 transition
// handler and the isolated pre-v2 task_created compatibility entry point.
type PluginStepParams struct {
	PluginID    string `json:"plugin_id"`
	PluginRef   string `json:"plugin_ref,omitempty"`
	RevisionID  string `json:"revision_id,omitempty"`
	RevisionNo  int64  `json:"revision_no,omitempty"`
	TreeHash    string `json:"tree_hash,omitempty"`
	RemoteRoot  string `json:"remote_root,omitempty"`
	StepID      string `json:"step_id"`
	SessionID   string `json:"session_id"`
	UserInput   string `json:"user_input"`
	IsColdStart bool   `json:"is_cold_start"`
	HandOff     *bool  `json:"hand_off,omitempty"`
	PreflightID string `json:"preflight_id,omitempty"`

	// ChatSessionID identifies the ChatAgent turn for task lifecycle context.
	ChatSessionID string `json:"chat_session_id,omitempty"`

	// PluginMode is "auto" | "dynamic" — resolved from the conversation request and
	// persisted into params so that OnSubAgentDone can branch correctly even when
	// reconstructing PluginChatContext from the DB (hooks.go path).
	PluginMode string `json:"plugin_mode,omitempty"`

	// RetryHint is a runtime instruction generated by ChatAgent for partial/full retries.
	// It is appended to the step objective before the SubAgent runs, and is NOT persisted
	// back to state.yml — it only affects the current execution.
	RetryHint string `json:"retry_hint,omitempty"`

	// PartialIndices maps slot → list of list_index values that should be
	// overwritten (not appended) when the SubAgent saves those artifacts.
	// Nil / empty means full write (append for list, overwrite for single).
	// Example: {"material_images": [1]} — only slot entry at list_index=1 is replaced.
	PartialIndices map[string][]int `json:"partial_indices,omitempty"`

	// HistoryFilesPerTurn carries the full per-turn user attachment index so the
	// SubAgent can access uploaded files via read_user_attachment / find_user_attachment.
	// Key = conversation turn sequence (string), value = list of absolute file paths.
	HistoryFilesPerTurn map[string][]string `json:"history_files_per_turn,omitempty"`
	ParentAgenticConfig map[string]any      `json:"parent_agentic_config,omitempty"`

	// Filters carries retrieval filters (e.g. kb_id) from the chat session into plugin steps.
	Filters map[string]any `json:"filters,omitempty"`

	// UserID is the chat user id for KB ACL and signed static-file URLs.
	UserID string `json:"user_id,omitempty"`

	// RequiredOutputs is compiled by Go. Outputs not listed here are valid
	// conditional products but do not gate attempt success.
	RequiredOutputs []string `json:"required_outputs,omitempty"`
}

// asMap serialises the params into the generic map expected by subagent.RunRequest.Params.
func (p PluginStepParams) asMap() map[string]any {
	m := map[string]any{
		"plugin_id":     p.PluginID,
		"step_id":       p.StepID,
		"session_id":    p.SessionID,
		"user_input":    p.UserInput,
		"is_cold_start": p.IsColdStart,
	}
	if p.PluginMode != "" {
		m["plugin_mode"] = p.PluginMode
	}
	if p.HandOff != nil {
		m["hand_off"] = *p.HandOff
	}
	if p.PreflightID != "" {
		m["preflight_id"] = p.PreflightID
	}
	if p.ChatSessionID != "" {
		m["chat_session_id"] = p.ChatSessionID
	}
	if p.RetryHint != "" {
		m["retry_hint"] = p.RetryHint
	}
	if len(p.PartialIndices) > 0 {
		m["partial_indices"] = p.PartialIndices
	}
	if len(p.HistoryFilesPerTurn) > 0 {
		m["history_files_per_turn"] = p.HistoryFilesPerTurn
	}
	if len(p.Filters) > 0 {
		m["filters"] = p.Filters
	}
	if p.UserID != "" {
		m["user_id"] = p.UserID
	}
	return m
}

// PluginChatContext carries plugin identifiers threaded through the SubAgent event loop.
type PluginChatContext struct {
	SessionID           string
	PluginID            string
	StepID              string
	ConvID              string
	UserID              string
	PluginMode          string // "auto" | "dynamic"
	ChatSessionID       string
	HistoryFilesPerTurn map[string][]string
	HandOff             *bool
}

func conversationPreflight(ctx context.Context, db *gorm.DB, convID string) (map[string]any, map[string]any) {
	var conv orm.Conversation
	if db == nil || db.WithContext(ctx).Select("ext").Where("id = ?", convID).First(&conv).Error != nil {
		return nil, nil
	}
	ext := map[string]any{}
	if json.Unmarshal(conv.Ext, &ext) != nil {
		return nil, nil
	}
	preflight, _ := ext["plugin_preflight"].(map[string]any)
	return ext, preflight
}

func validateConversationPreflight(ctx context.Context, db *gorm.DB, convID, preflightID string) error {
	if strings.TrimSpace(preflightID) == "" {
		return nil // backward compatibility for callers that predate trigger preflight
	}
	_, preflight := conversationPreflight(ctx, db, convID)
	if preflight == nil || fmt.Sprint(preflight["preflight_id"]) != preflightID {
		return fmt.Errorf("plugin: prepared preflight is missing or stale")
	}
	if fmt.Sprint(preflight["status"]) != "ready" {
		return fmt.Errorf("plugin: preflight is not ready")
	}
	return nil
}

func consumeConversationPreflight(ctx context.Context, db *gorm.DB, convID, preflightID string) error {
	if strings.TrimSpace(preflightID) == "" {
		return nil
	}
	ext, preflight := conversationPreflight(ctx, db, convID)
	if preflight == nil || fmt.Sprint(preflight["preflight_id"]) != preflightID {
		return fmt.Errorf("plugin: prepared preflight changed before it could be consumed")
	}
	delete(ext, "plugin_preflight")
	raw, _ := json.Marshal(ext)
	return db.WithContext(ctx).Model(&orm.Conversation{}).Where("id = ?", convID).Update("ext", raw).Error
}

// HandlePluginStepCreated is the compatibility entry point for pre-v2
// task_created events. Graph-engine sessions use the synchronous transition API.
func HandlePluginStepCreated(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	convID, historyID, userID string,
	taskID, title, objective string,
	params PluginStepParams,
	inputKeys, outputKeys []string,
	llmConfig map[string]any,
	toolConfig map[string]any,
) (sessionID string, returnedTaskID string, pluginCompleted bool, err error) {
	if params.SessionID != "" {
		session, getErr := GetSession(ctx, db, params.SessionID)
		if getErr == nil && session.GraphSchemaVersion != "" {
			return "", taskID, false, fmt.Errorf("plugin: task_created is disabled for graph-engine session %s", params.SessionID)
		}
	}
	if params.StepID == "__end__" {
		if params.SessionID == "" {
			return "", taskID, false, fmt.Errorf("plugin: session_id required for legacy __end__ signal")
		}
		if _, createErr := CreateSessionStep(ctx, db, params.SessionID, "__end__", "__end__", 1); createErr != nil {
			return "", taskID, false, fmt.Errorf("plugin: persist legacy __end__: %w", createErr)
		}
		_ = UpdateStepStatus(ctx, db, "__end__", StepStatusSucceeded)
		if updateErr := UpdateSessionStatus(ctx, db, params.SessionID, SessionStatusCompleted); updateErr != nil {
			return "", taskID, false, fmt.Errorf("plugin: complete legacy session: %w", updateErr)
		}
		_ = taskcenter.UpdateTaskStatusBySession(ctx, db, params.SessionID, "succeeded")
		clearGeneratingChatStatus(ctx, stateStore, convID)
		return params.SessionID, taskID, true, nil
	}
	return launchPluginAttempt(
		ctx, db, stateStore, convID, historyID, userID, taskID, title, objective,
		params, inputKeys, outputKeys, llmConfig, toolConfig, true, true,
	)
}

// launchPluginAttempt persists and launches an attempt after its caller has
// performed admission. New transitions pass legacyEvent=false so the legacy
// single-current compatibility field is not mutated.
func launchPluginAttempt(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	convID, historyID, userID string,
	taskID, title, objective string,
	params PluginStepParams,
	inputKeys, outputKeys []string,
	llmConfig map[string]any,
	toolConfig map[string]any,
	legacyEvent bool,
	launchNow bool,
) (sessionID string, returnedTaskID string, pluginCompleted bool, err error) {
	pluginID := params.PluginID
	stepID := params.StepID
	isCold := params.IsColdStart
	returnedTaskID = taskID
	fmt.Printf("[plugin] attempt launch requested conv=%s session=%s plugin=%s step=%s task=%s cold=%t mode=%s legacy=%t\n",
		convID, params.SessionID, pluginID, stepID, taskID, isCold, params.PluginMode, legacyEvent)
	if params.ChatSessionID != "" {
		fmt.Printf("[plugin] task_created chat sid conv=%s chat_sid=%s plugin=%s step=%s task=%s\n",
			convID, params.ChatSessionID, pluginID, stepID, taskID)
	}

	if isCold {
		fmt.Printf("[plugin] cold-start branch conv=%s plugin=%s step=%s task=%s\n", convID, pluginID, stepID, taskID)
		psID := "ps_" + common.GenerateID()
		currentStepID := ""
		if legacyEvent {
			currentStepID = stepID
		}
		coldErr := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
			existing, gErr := GetActiveSession(ctx, tx, convID)
			if gErr != nil {
				return fmt.Errorf("plugin: check active session: %w", gErr)
			}
			if existing != nil {
				return fmt.Errorf("plugin: active session already exists (id=%s)", existing.ID)
			}
			if pErr := validateConversationPreflight(ctx, tx, convID, params.PreflightID); pErr != nil {
				return pErr
			}
			if _, sErr := CreateSession(ctx, tx, CreateSessionInput{
				SessionID:      psID,
				ConversationID: convID,
				PluginID:       pluginID,
				PluginRef:      params.PluginRef, PluginRevisionID: params.RevisionID, PluginRevisionNo: params.RevisionNo, PluginTreeHash: params.TreeHash, PluginRemoteRoot: params.RemoteRoot,
				TriggerHistoryID: historyID,
				CurrentStepID:    currentStepID,
				CreateUserID:     userID,
			}); sErr != nil {
				return fmt.Errorf("plugin: create session: %w", sErr)
			}
			if strings.TrimSpace(params.UserInput) != "" {
				intentJSON, _ := json.Marshal(map[string]string{"text": params.UserInput})
				if err := tx.WithContext(ctx).Model(&orm.PluginSession{}).
					Where("id = ?", psID).
					Update("intent_context", string(intentJSON)).Error; err != nil {
					return fmt.Errorf("plugin: persist launch intent: %w", err)
				}
			}
			return consumeConversationPreflight(ctx, tx, convID, params.PreflightID)
		})
		if coldErr != nil {
			return "", "", false, coldErr
		}
		sessionID = psID
		fmt.Printf("[plugin] plugin session created conv=%s session=%s plugin=%s legacy_current_step=%s\n",
			convID, sessionID, pluginID, currentStepID)
		// Register a TaskCenter record for this plugin run so the user can track it.
		// Prefer conversation display_name as the task title so the task center shows
		// a human-readable conversation title instead of a raw plugin/step identifier.
		tcTitle := pluginID
		if title != "" {
			tcTitle = title
		}
		if db != nil {
			var conv orm.Conversation
			if err := db.WithContext(ctx).
				Select("display_name").
				Where("id = ?", convID).
				First(&conv).Error; err == nil && conv.DisplayName != "" {
				tcTitle = conv.DisplayName
			}
		}
		_ = taskcenter.CreateTask(ctx, db, &orm.TaskCenterTask{
			UserID:          userID,
			ConversationID:  convID,
			PluginSessionID: &sessionID,
			TaskType:        "plugin_run",
			Title:           &tcTitle,
			Status:          "running",
		})
		fmt.Printf("[plugin] taskcenter plugin_run ensured conv=%s session=%s plugin=%s\n",
			convID, sessionID, pluginID)
	} else {
		sessionID = params.SessionID
		fmt.Printf("[plugin] advance branch conv=%s session=%s plugin=%s step=%s task=%s\n",
			convID, sessionID, pluginID, stepID, taskID)
		if sessionID == "" {
			return "", "", false, fmt.Errorf("plugin: session_id required for non-cold-start step")
		}
		// Skip step advancement for dismissed sessions to prevent stale writes.
		existingSess, dsErr := GetSession(ctx, db, sessionID)
		if dsErr == nil && existingSess.Dismissed {
			return sessionID, taskID, false, fmt.Errorf("plugin: session %s is dismissed, skipping step advancement", sessionID)
		}
		if legacyEvent {
			if uErr := UpdateSessionCurrentStep(ctx, db, sessionID, stepID); uErr != nil {
				return sessionID, taskID, false, fmt.Errorf("plugin: update legacy current step: %w", uErr)
			} else {
				fmt.Printf("[plugin] legacy session current_step updated conv=%s session=%s step=%s\n",
					convID, sessionID, stepID)
			}
		}
		// Ensure session is marked active when a new step starts (e.g. auto-advance via ChatAgent).
		if uErr := UpdateSessionStatus(ctx, db, sessionID, SessionStatusActive); uErr != nil {
			return sessionID, taskID, false, fmt.Errorf("plugin: activate session: %w", uErr)
		} else {
			fmt.Printf("[plugin] session status active conv=%s session=%s step=%s\n",
				convID, sessionID, stepID)
		}
		// A retry/rewind reopens a failed plugin run. Reset TaskCenter even when its
		// previous value was terminal so later success can be synchronized normally.
		_ = db.WithContext(ctx).Model(&orm.TaskCenterTask{}).
			Where("plugin_session_id = ?", sessionID).
			Updates(map[string]any{"status": "running", "updated_at": time.Now().UTC()}).Error
	}

	// Inject artifacts from previous steps into objective, then append retry_hint if present.
	enrichedObjective := objective
	if params.RetryHint != "" {
		enrichedObjective += "\n\n--- Retry instruction (runtime only, not part of permanent prompt) ---\n" + params.RetryHint
	}

	// Create sub_agent_tasks record.
	rawParamsMap := map[string]any{
		"plugin_id":     pluginID,
		"step_id":       stepID,
		"session_id":    sessionID,
		"user_input":    params.UserInput,
		"is_cold_start": isCold,
	}
	if !legacyEvent {
		// Compiled graph outputs are material guarantees. A v2 attempt cannot
		// succeed unless every declared output was actually persisted.
		rawParamsMap["required_output_artifact_keys"] = params.RequiredOutputs
	}
	if params.HandOff != nil {
		rawParamsMap["hand_off"] = *params.HandOff
	}
	if params.PreflightID != "" {
		rawParamsMap["preflight_id"] = params.PreflightID
	}
	if params.PluginMode != "" {
		rawParamsMap["plugin_mode"] = params.PluginMode
	}
	if params.ChatSessionID != "" {
		rawParamsMap["chat_session_id"] = params.ChatSessionID
	}
	if params.RetryHint != "" {
		rawParamsMap["retry_hint"] = params.RetryHint
	}
	if len(params.PartialIndices) > 0 {
		rawParamsMap["partial_indices"] = params.PartialIndices
	}
	if len(params.HistoryFilesPerTurn) > 0 {
		rawParamsMap["history_files_per_turn"] = params.HistoryFilesPerTurn
	}
	filters := params.Filters
	if len(filters) == 0 {
		filters = filtersFromConversation(db, convID)
		if len(filters) > 0 {
			params.Filters = filters
		}
	}
	if len(filters) > 0 {
		rawParamsMap["filters"] = filters
	}
	if params.UserID != "" {
		rawParamsMap["user_id"] = params.UserID
	}
	rawParams, _ := json.Marshal(rawParamsMap)
	inputJSON, _ := json.Marshal(inputKeys)
	outputJSON, _ := json.Marshal(outputKeys)
	task, cErr := subagent.CreateTask(ctx, db, subagent.CreateTaskInput{
		TaskID:           taskID,
		ConversationID:   convID,
		TriggerHistoryID: historyID,
		AgentType:        "plugin_step",
		Title:            pluginID + ":" + stepID,
		Objective:        enrichedObjective,
		Mode:             "manual",
		Params:           rawParams,
		InputSlots:       inputJSON,
		OutputSlots:      outputJSON,
		WorkspacePath:    subagent.WorkspacePath(userID, taskID),
		CreateUserID:     userID,
	})
	if cErr != nil {
		return "", sessionID, false, fmt.Errorf("plugin: create sub_agent_task: %w", cErr)
	}
	fmt.Printf("[plugin] sub_agent_task created conv=%s session=%s plugin=%s step=%s task=%s workspace=%s\n",
		convID, sessionID, pluginID, stepID, task.ID, task.WorkspacePath)

	// Create plugin_session_steps record.
	attempt, attemptErr := NextAttempt(ctx, db, sessionID, stepID)
	if attemptErr != nil {
		return sessionID, task.ID, false, fmt.Errorf("plugin: allocate attempt: %w", attemptErr)
	}
	if _, stepErr := CreateSessionStep(ctx, db, sessionID, stepID, task.ID, attempt); stepErr != nil {
		return sessionID, task.ID, false, fmt.Errorf("plugin: create session step: %w", stepErr)
	} else {
		fmt.Printf("[plugin] plugin_session_step created conv=%s session=%s step=%s task=%s attempt=%d\n",
			convID, sessionID, stepID, task.ID, attempt)
	}
	runParams := map[string]any{
		"plugin_id":  pluginID,
		"step_id":    stepID,
		"session_id": sessionID,
	}
	if len(params.HistoryFilesPerTurn) > 0 {
		runParams["history_files_per_turn"] = params.HistoryFilesPerTurn
	}
	if len(params.ParentAgenticConfig) > 0 {
		runParams["parent_agentic_config"] = params.ParentAgenticConfig
	}
	runRequest := subagent.RunRequest{
		TaskID: task.ID, AgentType: "plugin_step", WorkspacePath: task.WorkspacePath,
		Params: runParams, DBDSN: subagent.DBDSN(), Resume: false,
		LLMConfig: llmConfig, ToolConfig: toolConfig,
	}
	if enqueueErr := enqueuePluginAttemptRunner(ctx, db, runRequest); enqueueErr != nil {
		return sessionID, task.ID, false, fmt.Errorf("plugin: enqueue attempt runner: %w", enqueueErr)
	}

	if launchNow {
		dispatchPluginAttemptRunner(db, stateStore, task.ID)
	}

	return sessionID, task.ID, false, nil
}

func enqueuePluginAttemptRunner(ctx context.Context, db *gorm.DB, request subagent.RunRequest) error {
	payload, err := json.Marshal(request)
	if err != nil {
		return err
	}
	now := time.Now().UTC()
	return db.WithContext(ctx).Create(&orm.PluginRunOutbox{
		TaskID: request.TaskID, Payload: payload, Status: "pending", CreatedAt: now, UpdatedAt: now,
	}).Error
}

// dispatchPluginAttemptRunner atomically claims a durable outbox item. It is
// called only after the transaction that accepted the transition has committed.
func dispatchPluginAttemptRunner(db *gorm.DB, stateStore state.Store, taskID string) {
	var row orm.PluginRunOutbox
	claimed := false
	if err := db.WithContext(context.Background()).Transaction(func(tx *gorm.DB) error {
		result := tx.Model(&orm.PluginRunOutbox{}).
			Where("task_id = ? AND status = ?", taskID, "pending").
			Updates(map[string]any{"status": "dispatching", "updated_at": time.Now().UTC()})
		if result.Error != nil || result.RowsAffected != 1 {
			return result.Error
		}
		if err := tx.Where("task_id = ?", taskID).First(&row).Error; err != nil {
			return err
		}
		var task orm.SubAgentTask
		if err := tx.Select("status").Where("id = ?", taskID).First(&task).Error; err != nil {
			return err
		}
		if task.Status == subagent.StatusSucceeded || task.Status == subagent.StatusFailed || task.Status == subagent.StatusInterrupted || task.Status == subagent.StatusCanceled {
			return tx.Model(&orm.PluginRunOutbox{}).Where("task_id = ?", taskID).
				Updates(map[string]any{"status": "completed", "updated_at": time.Now().UTC()}).Error
		}
		claimed = true
		return nil
	}); err != nil || !claimed {
		return
	}
	var request subagent.RunRequest
	if err := json.Unmarshal(row.Payload, &request); err != nil {
		_ = db.Model(&orm.PluginRunOutbox{}).Where("task_id = ?", taskID).
			Updates(map[string]any{"status": "failed", "last_error": err.Error(), "updated_at": time.Now().UTC()}).Error
		_ = subagent.UpdateFinalStatus(context.Background(), db, taskID, subagent.StatusFailed, "invalid plugin run outbox payload")
		_ = UpdateStepStatus(context.Background(), db, taskID, StepStatusFailed)
		if pctx := loadPluginChatContextFromDB(context.Background(), db, taskID); pctx != nil {
			_ = UpdateSessionStatus(context.Background(), db, pctx.SessionID, SessionStatusWaiting)
		}
		return
	}
	_ = subagent.WriteStatus(context.Background(), stateStore, taskID, map[string]any{
		"status": subagent.StatusPending, "progress": 0,
	})
	go func() {
		err := subagent.Run(context.Background(), db, stateStore, request)
		status, lastError := "completed", ""
		if err != nil {
			status, lastError = "failed", err.Error()
		}
		_ = db.Model(&orm.PluginRunOutbox{}).Where("task_id = ?", taskID).
			Updates(map[string]any{"status": status, "last_error": lastError, "updated_at": time.Now().UTC()}).Error
	}()
}

// OnSubAgentDone is called when a plugin_step task reaches terminal status.
// It mirrors the step status and handles auto/dynamic advance logic.
//
// Successful v2 attempts freeze their route decision and let the graph
// projector determine completion. Legacy sessions retain their waiting flow.
func OnSubAgentDone(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	taskID, status, summary string,
	onSSE func(eventType string, payload map[string]any),
	pctx *PluginChatContext,
) {
	_ = UpdateStepStatus(ctx, db, taskID, status)
	stepFailed := status != subagent.StatusSucceeded && status != subagent.StatusInterrupted
	sessionCompleted := false
	if status == subagent.StatusSucceeded && pctx != nil && pctx.SessionID != "" {
		if err := freezeRouteDecision(ctx, db, pctx.SessionID, pctx.StepID, taskID); err != nil {
			fmt.Printf("[plugin] freeze route decision failed session=%s step=%s err=%v\n", pctx.SessionID, pctx.StepID, err)
		} else {
			var session orm.PluginSession
			if db.WithContext(ctx).Select("status").Where("id = ?", pctx.SessionID).First(&session).Error == nil {
				sessionCompleted = session.Status == SessionStatusCompleted
			}
		}
	}

	if stepFailed {
		// Non-succeeded, non-interrupted (i.e. truly failed) steps: notify the frontend
		// and mark the session failed. Auto mode still asks DriverAgent to diagnose
		// and recommend retry/rewind; dynamic mode leaves the failure for the user.
		if pctx != nil {
			onSSE("plugin_error", map[string]any{
				"session_id": pctx.SessionID,
				"step_id":    pctx.StepID,
				"message":    summary,
			})
		}
		if pctx != nil && pctx.SessionID != "" {
			_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusFailed)
			_ = taskcenter.UpdateTaskStatusBySession(ctx, db, pctx.SessionID, "failed")
			clearGeneratingChatStatus(ctx, stateStore, pctx.ConvID)
			go OnSubAgentDoneSnapshot(context.Background(), db, pctx)
		}
	}

	if pctx == nil {
		return
	}

	// Check whether sibling steps in the same session are still running.
	// If any step is still running, emit step_parallel_done for UI progress and wait.
	// Only the last step to complete triggers the advance logic.
	// Note: UpdateStepStatus above has already set this step to a terminal status,
	// so the running count will not include the current step.
	if pctx.SessionID != "" {
		var runningCount int64
		db.WithContext(ctx).Model(&orm.PluginSessionStep{}).
			Where("session_id = ? AND status = ?", pctx.SessionID, StepStatusRunning).
			Count(&runningCount)
		if runningCount > 0 {
			onSSE("step_partial_done", map[string]any{
				"session_id": pctx.SessionID,
				"step_id":    pctx.StepID,
			})
			return
		}
	}

	if sessionCompleted {
		_ = taskcenter.UpdateTaskStatusBySession(ctx, db, pctx.SessionID, "succeeded")
		clearGeneratingChatStatus(ctx, stateStore, pctx.ConvID)
		onSSE("plugin_completed", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
		})
		go OnSubAgentDoneSnapshot(context.Background(), db, pctx)
		return
	}

	// Determine mode: use context-level PluginMode (set from request body during HandlePluginStepCreated).
	// Falls back to "dynamic" if not set. Env-var defaultMode() is no longer used.
	mode := pctx.PluginMode
	if mode != "auto" && mode != "dynamic" {
		mode = "dynamic"
	}
	fmt.Printf("[plugin] sub_agent terminal conv=%s session=%s step=%s task=%s status=%s mode=%s summary_len=%d\n",
		pctx.ConvID, pctx.SessionID, pctx.StepID, taskID, status, mode, len(summary))
	if stepFailed {
		if mode == "auto" {
			go advanceAutoMode(context.Background(), db, stateStore, status, summary, onSSE, pctx)
		}
		return
	}

	handOff := true // legacy tasks only had the hand-off advancement tool by default
	if pctx.HandOff != nil {
		handOff = *pctx.HandOff
	}
	if !handOff {
		_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
		onSSE("step_waiting", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
			"reason":     "inline_complete",
		})
		go OnSubAgentDoneSnapshot(context.Background(), db, pctx)
		return
	}

	if mode == "auto" {
		// Interrupted steps should not be auto-advanced: surface the interruption to the user
		// so they can explicitly choose to continue (checkpoint resume) or retry.
		if status == subagent.StatusInterrupted {
			_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
			onSSE("step_waiting", map[string]any{
				"session_id": pctx.SessionID,
				"step_id":    pctx.StepID,
				"reason":     "interrupted",
			})
			return
		}
		// Use a detached context: ctx originates from the SubAgent Run loop and is
		// cancelled as soon as Run returns, before this goroutine loads LLM config.
		go advanceAutoMode(context.Background(), db, stateStore, status, summary, onSSE, pctx)
	} else {
		_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
		onSSE("step_waiting", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
			"reason":     "dynamic_pause",
		})
	}
	// Write content_snapshot to all selected revisions for this step.
	go OnSubAgentDoneSnapshot(context.Background(), db, pctx)
}

func clearGeneratingChatStatus(ctx context.Context, stateStore state.Store, convID string) {
	if stateStore == nil || strings.TrimSpace(convID) == "" {
		return
	}
	key := fmt.Sprintf("rag/chat/status:%s", convID)
	entries, err := stateStore.HGetAll(ctx, key)
	if err != nil {
		return
	}
	var fields []string
	for historyID, raw := range entries {
		var st chatStatusCacheEntry
		if json.Unmarshal([]byte(raw), &st) != nil {
			continue
		}
		if st.Status == "generating" {
			fields = append(fields, historyID)
		}
	}
	if len(fields) > 0 {
		_ = stateStore.HDel(ctx, key, fields...)
	}
}

// advanceAutoMode calls DriverAgent and forwards its natural-language assessment to ChatAgent.
// ChatAgent then decides autonomously whether to advance, retry, or rewind.
// Go's graph projector determines session completion.
func advanceAutoMode(
	ctx context.Context,
	db *gorm.DB,
	stateStore state.Store,
	terminalStatus string,
	summary string,
	onSSE func(string, map[string]any),
	pctx *PluginChatContext,
) {
	// Enforce global max retries (non-plugin.yaml configurable).
	step, _ := GetLatestStep(ctx, db, pctx.SessionID, pctx.StepID)
	attempt := 0
	if step != nil {
		attempt = step.Attempt
	}
	if terminalStatus == subagent.StatusSucceeded && attempt >= defaultDriverMaxRetries {
		onSSE("max_retries_exceeded", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
			"attempt":    attempt,
		})
		// Treat as PASS — forward summary directly to ChatAgent without DriverAgent evaluation.
		pctxCopy := *pctx
		go func() {
			triggerNextChatTurn(pctxCopy.ConvID, pctxCopy.SessionID, pctxCopy.PluginID, pctxCopy.StepID,
				pctxCopy.PluginMode, pctxCopy.UserID, summary, func() {
					onSSE("auto_chat_started", map[string]any{
						"session_id":      pctxCopy.SessionID,
						"conversation_id": pctxCopy.ConvID,
						"driver_message":  summary,
					})
				}, "driver")
			checkAndFallbackIfStuck(ctx, db, stateStore, onSSE, &pctxCopy)
		}()
		return
	}

	// Load LLM config for DriverAgent.
	var llmCfg map[string]any
	if db != nil {
		if cfg, err := loadDriverLLMConfig(ctx, db, pctx.UserID); err == nil {
			llmCfg = cfg
		} else {
			fmt.Printf("[Plugin] loadDriverLLMConfig failed user=%s err=%v\n", pctx.UserID, err)
		}
	}
	if len(llmCfg) == 0 {
		fmt.Printf("[Plugin] driver LLM config empty for user=%s session=%s step=%s\n",
			pctx.UserID, pctx.SessionID, pctx.StepID)
	}

	// Build plugin artifacts summary for DriverAgent evaluation.
	artifactsSummary, _ := buildPluginArtifactsSummary(ctx, db, pctx.SessionID, pctx.StepID)

	driverInput := fmt.Sprintf("Terminal status: %s\nAttempt: %d\n%s", terminalStatus, attempt, summary)
	driverMsg, fallback := callDriverAgent(pctx.PluginID, pctx.StepID, driverInput, pctx.SessionID,
		pctx.HistoryFilesPerTurn, llmCfg, artifactsSummary)

	if fallback {
		// DriverAgent failed: degrade to dynamic (notify user, do not auto-advance).
		onSSE("driver_fallback", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
			"reason":     "driver_unavailable",
		})
		_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
		onSSE("step_waiting", map[string]any{
			"session_id": pctx.SessionID,
			"step_id":    pctx.StepID,
			"reason":     "driver_fallback",
		})
		return
	}

	// Emit driver_input so the frontend can render the DriverAgent assessment.
	onSSE("driver_input", map[string]any{
		"session_id": pctx.SessionID,
		"step_id":    pctx.StepID,
		"message":    driverMsg,
	})
	pctxCopy := *pctx
	go func() {
		triggerNextChatTurn(pctxCopy.ConvID, pctxCopy.SessionID, pctxCopy.PluginID, pctxCopy.StepID,
			pctxCopy.PluginMode, pctxCopy.UserID, driverMsg, func() {
				// Emit after core has accepted the request and set Redis generating status,
				// so the frontend resume SSE does not race with stream setup.
				onSSE("auto_chat_started", map[string]any{
					"session_id":      pctxCopy.SessionID,
					"conversation_id": pctxCopy.ConvID,
					"driver_message":  driverMsg,
				})
			}, "driver")
		checkAndFallbackIfStuck(ctx, db, stateStore, onSSE, &pctxCopy)
	}()
}

// triggerNextChatTurn sends a synthetic POST /conversations:chat to Go core to trigger
// the next ChatAgent round. This ensures history persistence, applyChatRuntimeConfigs,
// and all other Go-side pipeline steps run exactly as in a real user turn.
func triggerNextChatTurn(
	convID, sessionID, pluginID, currentStep, pluginMode, userID, syntheticMsg string,
	onReady func(),
	syntheticSource string,
) {
	coreURL := common.CoreSelfEndpoint() + "/conversations:chat"
	pluginCtx := map[string]any{
		"session_id":   sessionID,
		"plugin_id":    pluginID,
		"current_step": currentStep,
		"plugin_mode":  pluginMode,
	}
	if syntheticSource != "" {
		pluginCtx["synthetic_source"] = syntheticSource
	}
	reqBody := map[string]any{
		"query":           syntheticMsg,
		"conversation_id": convID,
		// stream=true is required so that task_created events emitted by the ChatAgent
		// are written to the Redis SSE buffer and delivered to the frontend.
		// Non-streaming mode skips the event pipeline entirely.
		"stream":         true,
		"mode":           "auto",
		"input":          []map[string]any{{"input_type": "text", "text": syntheticMsg}},
		"plugin_context": pluginCtx,
	}
	if searchConfig := loadConversationSearchConfig(store.DB(), convID); len(searchConfig) > 0 {
		reqBody["conversation"] = map[string]any{"search_config": searchConfig}
	}
	body, _ := json.Marshal(reqBody)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, coreURL, bytes.NewReader(body))
	if err != nil {
		fmt.Printf("[Plugin] triggerNextChatTurn: build request: %v\n", err)
		return
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "text/event-stream")
	req.Header.Set("X-User-Id", userID)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		fmt.Printf("[Plugin] triggerNextChatTurn: send request: %v\n", err)
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		fmt.Printf("[Plugin] triggerNextChatTurn: core returned %d\n", resp.StatusCode)
		return
	}
	if onReady != nil {
		onReady()
	}
	// Drain the SSE response body. We do not relay the stream anywhere; Go core
	// writes all events (including task_created) directly to Redis. Draining is
	// required to keep the connection alive until the upstream finishes.
	buf := make([]byte, 4096)
	for {
		if _, err := resp.Body.Read(buf); err != nil {
			break
		}
	}
}

// checkAndFallbackIfStuck is called after triggerNextChatTurn returns (stream drained).
// If ChatAgent did not call advance_step the session remains active even though no
// SubAgent is running. This function detects that condition and demotes the session to
// waiting so the frontend can prompt the user for input.
func checkAndFallbackIfStuck(
	ctx context.Context,
	db *gorm.DB,
	_ state.Store,
	onSSE func(string, map[string]any),
	pctx *PluginChatContext,
) {
	// Brief pause to let any in-flight HandlePluginStepCreated DB writes settle.
	time.Sleep(500 * time.Millisecond)
	session, err := GetSession(ctx, db, pctx.SessionID)
	if err != nil || session == nil {
		return
	}
	if session.Status != SessionStatusActive {
		// Session was already advanced or completed — nothing to do.
		return
	}
	// A plugin_step SubAgent may still be running (advance_step succeeded); keep session active.
	var runningCount int64
	if err := db.WithContext(ctx).Model(&orm.PluginSessionStep{}).
		Where("session_id = ? AND status = ?", pctx.SessionID, StepStatusRunning).
		Count(&runningCount).Error; err == nil && runningCount > 0 {
		return
	}
	// Session is still active but no SubAgent is running: ChatAgent did not push a new step.
	_ = UpdateSessionStatus(ctx, db, pctx.SessionID, SessionStatusWaiting)
	onSSE("step_waiting", map[string]any{
		"session_id": pctx.SessionID,
		"step_id":    pctx.StepID,
		"reason":     "chat_agent_no_advance",
	})
}

// OnArtifactEvent is called when a plugin_step SubAgent emits an artifact event.
// It checks slot binding and writes plugin_slot_revisions if the artifact is bound.
// Caption embedded in the artifact value is written to sub_agent_artifacts.caption.
//
// For list-cardinality slots, the artifact value may carry a "list_index" field
// (written by save_artifact) that enables partial retry: only the revision at that
// index is replaced; other indices remain untouched.
// When "list_index" is absent the item is appended at the next available index.
func OnArtifactEvent(
	ctx context.Context,
	db *gorm.DB,
	taskID, slot string,
	pctx *PluginChatContext,
) {
	if pctx == nil {
		return
	}
	slotID, cardinality := resolveSlotBinding(pctx.PluginID, slot)
	if slotID == "" {
		return
	}
	attempt := 1
	step, _ := GetLatestStep(ctx, db, pctx.SessionID, pctx.StepID)
	if step != nil {
		attempt = step.Attempt
	}

	// For list slots, extract list_index from the artifact value if present.
	var listIndex *int
	if cardinality == "list" {
		listIndex = extractListIndex(ctx, db, taskID, slot)
	}

	// Extract caption from artifact value and write it to sub_agent_artifacts.caption.
	// PostgreSQL does not support UPDATE with ORDER BY/LIMIT, so we first fetch the
	// target row's primary key (task_id + slot + seq), then update by PK.
	if caption := extractCaption(ctx, db, taskID, slot); caption != "" {
		var target orm.SubAgentArtifact
		if db.WithContext(ctx).
			Where("task_id = ? AND slot = ?", taskID, slot).
			Order("seq DESC").
			First(&target).Error == nil {
			_ = db.WithContext(ctx).Model(&orm.SubAgentArtifact{}).
				Where("task_id = ? AND slot = ? AND seq = ?", target.TaskID, target.Slot, target.Seq).
				Update("caption", caption).Error
		}
	}

	rev, err := WriteSlotRevision(ctx, db,
		pctx.SessionID, slotID, slot, pctx.StepID, attempt, cardinality, listIndex)
	if err != nil {
		fmt.Printf("[Plugin] WriteSlotRevision failed: %v\n", err)
		return
	}

	// Back-fill list_index into sub_agent_artifacts.value so that HideSlotItem
	// can match the artifact row by list_index when the user deletes an item.
	// This is needed for append-mode artifacts where Python does not yet know
	// the list_index assigned by Go (sort_order was not passed to save_artifact).
	if cardinality == "list" && rev != nil && rev.ListIndex != nil {
		backfillArtifactListIndex(ctx, db, taskID, slot, *rev.ListIndex)
	}
}

// OnSubAgentDoneSnapshot back-fills artifact_seq on any AI slot revision that was
// written before the artifact row existed (i.e. artifact_seq is still NULL).
// This covers the race where WriteSlotRevision ran before save_artifact committed.
// Human revisions (change_source='human') are never touched.
func OnSubAgentDoneSnapshot(
	ctx context.Context,
	db *gorm.DB,
	pctx *PluginChatContext,
) {
	if pctx == nil {
		return
	}
	revisions, err := LoadSelectedSlots(ctx, db, pctx.SessionID)
	if err != nil {
		fmt.Printf("[Plugin] OnSubAgentDoneSnapshot: load slots: %v\n", err)
		return
	}

	step, _ := GetLatestStep(ctx, db, pctx.SessionID, pctx.StepID)
	if step == nil {
		return
	}

	for _, rev := range revisions {
		if rev.StepID != pctx.StepID || rev.Attempt != step.Attempt {
			continue
		}
		// Only fix AI revisions where artifact_seq was not resolved at write time.
		if rev.ChangeSource != "ai" || rev.ArtifactSeq != nil {
			continue
		}

		// Find the matching artifact row.
		var art orm.SubAgentArtifact
		if rev.ListIndex != nil {
			var candidates []orm.SubAgentArtifact
			db.WithContext(ctx).
				Where("task_id = ? AND slot = ?", step.TaskID, rev.Slot).
				Order("seq DESC").
				Find(&candidates)
			for _, c := range candidates {
				var v map[string]any
				if json.Unmarshal(c.Value, &v) != nil {
					continue
				}
				var liInt int
				switch idx := v["list_index"].(type) {
				case float64:
					liInt = int(idx)
				case int:
					liInt = idx
				default:
					continue
				}
				if liInt == *rev.ListIndex {
					art = c
					break
				}
			}
			if art.TaskID == "" {
				continue
			}
		} else {
			if err := db.WithContext(ctx).
				Where("task_id = ? AND slot = ?", step.TaskID, rev.Slot).
				Order("seq DESC").
				First(&art).Error; err != nil {
				continue
			}
		}

		seq := art.Seq
		if err := db.WithContext(ctx).Model(&orm.PluginSlotRevision{}).
			Where("id = ?", rev.ID).
			Update("artifact_seq", seq).Error; err != nil {
			fmt.Printf("[Plugin] OnSubAgentDoneSnapshot: backfill artifact_seq rev=%s: %v\n", rev.ID, err)
		}
	}
}

// extractListIndex reads the most recent artifact value for the given (taskID, slot)
// and returns the list_index embedded in the JSON value, or nil if absent.
func extractListIndex(ctx context.Context, db *gorm.DB, taskID, slot string) *int {
	var a orm.SubAgentArtifact
	err := db.WithContext(ctx).
		Where("task_id = ? AND slot = ?", taskID, slot).
		Order("seq DESC").
		First(&a).Error
	if err != nil {
		return nil
	}
	var v map[string]any
	if json.Unmarshal(a.Value, &v) != nil {
		return nil
	}
	raw, ok := v["list_index"]
	if !ok {
		return nil
	}
	switch idx := raw.(type) {
	case float64:
		i := int(idx)
		return &i
	case int:
		return &idx
	}
	return nil
}

// extractCaption reads the most recent artifact value for the given (taskID, slot)
// and returns the caption string embedded in the JSON value, or "" if absent.
func extractCaption(ctx context.Context, db *gorm.DB, taskID, slot string) string {
	var a orm.SubAgentArtifact
	err := db.WithContext(ctx).
		Where("task_id = ? AND slot = ?", taskID, slot).
		Order("seq DESC").
		First(&a).Error
	if err != nil {
		return ""
	}
	var v map[string]any
	if json.Unmarshal(a.Value, &v) != nil {
		return ""
	}
	if cap, ok := v["caption"].(string); ok {
		return strings.TrimSpace(cap)
	}
	return ""
}

// resolveSlotBinding looks up (slotID, cardinality) for a slot from the Python plugin API.
func resolveSlotBinding(pluginID, slot string) (slotID, cardinality string) {
	endpoint := common.ChatServiceEndpoint()
	url := fmt.Sprintf("%s/api/plugin/slot-binding?plugin_id=%s&slot=%s",
		endpoint, pluginID, slot)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return "", ""
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", ""
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", ""
	}
	var result struct {
		SlotID      string `json:"slot_id"`
		Cardinality string `json:"cardinality"`
	}
	if json.NewDecoder(resp.Body).Decode(&result) != nil {
		return "", ""
	}
	return result.SlotID, result.Cardinality
}

// defaultDriverMaxRetries is the global max retry count for DriverAgent RETRY verdicts.
// Not configurable per plugin.yaml — global platform setting only.
const defaultDriverMaxRetries = 3

// callDriverAgent posts to the Python DriverAgent endpoint and returns the natural-language
// assessment message and a fallback flag. On any error, fallback=true is returned.
// A retry (up to 1 time with 5s backoff) is performed before falling back.
func callDriverAgent(
	pluginID, stepID, stepResult, sessionID string,
	historyFilesPerTurn map[string][]string,
	llmConfig map[string]any,
	artifactsSummary string,
) (message string, fallback bool) {
	doCall := func() (string, bool) {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()
		reqBody := map[string]any{
			"plugin_id":   pluginID,
			"step_id":     stepID,
			"step_result": stepResult,
			"session_id":  sessionID,
		}
		if len(historyFilesPerTurn) > 0 {
			reqBody["history_files_per_turn"] = historyFilesPerTurn
		}
		if len(llmConfig) > 0 {
			reqBody["llm_config"] = llmConfig
		}
		if artifactsSummary != "" {
			reqBody["plugin_artifacts_summary"] = artifactsSummary
		}
		body, _ := json.Marshal(reqBody)
		req, err := http.NewRequestWithContext(ctx, http.MethodPost, driverEndpoint(), bytes.NewReader(body))
		if err != nil {
			return "", true
		}
		req.Header.Set("Content-Type", "application/json")
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return "", true
		}
		defer resp.Body.Close()
		var result struct {
			Message string `json:"message"`
		}
		if resp.StatusCode != http.StatusOK || json.NewDecoder(resp.Body).Decode(&result) != nil {
			return "", true
		}
		if strings.TrimSpace(result.Message) == "" {
			return "", true
		}
		return result.Message, false
	}

	msg, fb := doCall()
	if fb {
		// Retry once after 5s backoff.
		time.Sleep(5 * time.Second)
		msg, fb = doCall()
	}
	if fb {
		return fmt.Sprintf("Step %q completed.", stepID), true
	}
	return msg, false
}

// driverEndpoint returns the DriverAgent URL.
func driverEndpoint() string {
	return common.ChatServiceEndpoint() + "/api/plugin/driver"
}

// loadDriverLLMConfig loads the LLM config for a user to pass to the DriverAgent.
func loadDriverLLMConfig(ctx context.Context, db *gorm.DB, userID string) (map[string]any, error) {
	return modelconfig.LoadLLMConfig(ctx, db, userID)
}

// buildPluginArtifactsSummary builds a text summary of all artifacts produced in this
// plugin session and the current step, for injection into the DriverAgent evaluation context.
func buildPluginArtifactsSummary(ctx context.Context, db *gorm.DB, sessionID, stepID string) (string, error) {
	if db == nil || sessionID == "" {
		return "", nil
	}
	// Gather all sub_agent_artifacts for completed steps in this session.
	type artifactRow struct {
		Slot   string `gorm:"column:slot"`
		Value  []byte `gorm:"column:value"`
		TaskID string `gorm:"column:task_id"`
	}
	var rows []artifactRow
	err := db.WithContext(ctx).Raw(`
		SELECT sa.slot, sa.value, sa.task_id
		FROM sub_agent_artifacts sa
		JOIN plugin_session_steps pss ON pss.task_id = sa.task_id
		WHERE pss.session_id = ? AND pss.status = 'succeeded'
		ORDER BY sa.task_id, sa.slot, sa.seq
	`, sessionID).Scan(&rows).Error
	if err != nil || len(rows) == 0 {
		return "", err
	}
	var sb strings.Builder
	sb.WriteString("## Plugin session artifacts\n")
	for _, r := range rows {
		var v map[string]any
		if json.Unmarshal(r.Value, &v) == nil {
			if val, ok := v["value"]; ok {
				sb.WriteString(fmt.Sprintf("- %s: %v\n", r.Slot, val))
				continue
			}
		}
		sb.WriteString(fmt.Sprintf("- %s: %s\n", r.Slot, string(r.Value)))
	}
	return sb.String(), nil
}

// backfillArtifactListIndex patches the most-recent sub_agent_artifacts row for
// (taskID, slot) to embed {"list_index": listIndex} inside its value JSON.
// This ensures HideSlotItem can match artifacts by list_index even when the AI
// wrote the artifact in append-mode (no sort_order → no list_index in value at write time).
// Skipped silently if the row already contains the correct list_index.
func backfillArtifactListIndex(ctx context.Context, db *gorm.DB, taskID, slot string, listIndex int) {
	var art orm.SubAgentArtifact
	if err := db.WithContext(ctx).
		Where("task_id = ? AND slot = ?", taskID, slot).
		Order("seq DESC").
		First(&art).Error; err != nil {
		return
	}
	var v map[string]any
	if json.Unmarshal(art.Value, &v) != nil {
		return
	}
	// Already correct — no update needed.
	if existing, ok := v["list_index"]; ok {
		switch idx := existing.(type) {
		case float64:
			if int(idx) == listIndex {
				return
			}
		case int:
			if idx == listIndex {
				return
			}
		}
	}
	v["list_index"] = listIndex
	newVal, err := json.Marshal(v)
	if err != nil {
		return
	}
	_ = db.WithContext(ctx).Model(&orm.SubAgentArtifact{}).
		Where("task_id = ? AND slot = ? AND seq = ?", art.TaskID, art.Slot, art.Seq).
		Update("value", newVal).Error
}
