ALTER TABLE plugin_drafts
  ADD COLUMN IF NOT EXISTS plugin_yaml_content TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS state_yaml_content  TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS scenario_content    TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS scripts_content     TEXT NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS generate_status     VARCHAR(16) NOT NULL DEFAULT '';
