ALTER TABLE public.personal_resources
    ADD COLUMN IF NOT EXISTS auto_evo BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS auto_evo_apply_status VARCHAR(32) NOT NULL DEFAULT 'idle',
    ADD COLUMN IF NOT EXISTS auto_evo_generation BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS auto_evo_started_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS auto_evo_finished_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS auto_evo_error TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ext JSON,
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS updated_by_name VARCHAR(255) NOT NULL DEFAULT '';
